### ISSUE TITLE
Could not import model

### ISSUE THREAD

**Issue by unusualmutant** [Shpota/goxygen#91] opened 2020-10-30 11:20 UTC
I apologize in advance for my ignorance as this might be something trivial, but I am completely new to golang.

I generated a project with angular and mysql, but get errors in db.go and app_test.go. The project name is "buk":

![image](https://user-images.githubusercontent.com/50904772/97699232-12605e00-1aaa-11eb-8ed5-156f4d1f68e3.png)

![image](https://user-images.githubusercontent.com/50904772/97699116-e7760a00-1aa9-11eb-9886-a7217b563e99.png)

![image](https://user-images.githubusercontent.com/50904772/97699268-2310d400-1aaa-11eb-86d6-1dd647f78f34.png)

**Comment by Shpota** [comment] 2020-10-30 11:28
Does the application run if you start it using `docker-compose`?
In your case, you can run these two commands and check.
```
cd buk
docker-compose up
```

**Comment by unusualmutant** [comment] 2020-10-31 09:34
No, it fails when trying to go build:

![image](https://user-images.githubusercontent.com/50904772/97775879-72b3d600-1b64-11eb-9750-9b59f6f1bb13.png)

This is on Windows and the GOPATH is set to my git root folder.

**Comment by Shpota** [comment] 2020-10-31 14:25
Thank you for the information. It looks like a bug, but I did not manage to reproduce it so far (I have a Mac machine). I will find a Windows machine soon, and I will be able to fix the issue.

In the meantime, may I ask you to help me debug the issue? Could you please edit the `Dockerfile` adding a new line to the build instructions so that the go-related block will look like this:
```
FROM golang:1.15.1-alpine3.12 AS GO_BUILD
RUN go env
COPY server /server
WORKDIR /server
RUN go build -o /go/bin/server
```
After it has been saved, run 
```
docker-compose build
```
And let me know what was the output of the new instruction (`RUN go env`). This wold print the Go setup inside the Docker build.

**Comment by unusualmutant** [comment] 2020-10-31 16:03
Of course, and thank you for taking the time to help. Here is the output:

db uses an image, skipping
Building app
Step 1/13 : FROM node:12.18.3-alpine3.12 AS JS_BUILD
 ---> 73e8a4cf7fa8
Step 2/13 : COPY webapp /webapp
 ---> Using cache
 ---> 0d3728380fc8
Step 3/13 : WORKDIR /webapp
 ---> Using cache
 ---> 227d232430bd
Step 4/13 : RUN npm install && npm run build
 ---> Using cache
 ---> 0034b54a54d3

Step 5/13 : FROM golang:1.15.1-alpine3.12 AS GO_BUILD
 ---> f328e14e69e4
Step 6/13 : RUN go env
 ---> Running in e99bc858dedb
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build086502159=/tmp/go-build -gno-record-gcc-switches"
Removing intermediate container e99bc858dedb
 ---> acec9b461b46
Step 7/13 : COPY server /server
 ---> 5f11b99954c5
Step 8/13 : WORKDIR /server
 ---> Running in d25588d85aeb
Removing intermediate container d25588d85aeb
 ---> a620ee17bbe3
Step 9/13 : RUN go build -o /go/bin/server
 ---> Running in 1ddd4fad702e
go: downloading github.com/go-sql-driver/mysql v1.5.0
db/db.go:5:2: package model is not in GOROOT (/usr/local/go/src/model)
ERROR: Service 'app' failed to build : The command '/bin/sh -c go build -o /go/bin/server' returned a non-zero code: 1

**Comment by unusualmutant** [comment] 2020-10-31 16:04
For some reason if I type "go env GOPATH", I get at different result:

D:\git\buk>go env GOPATH
d:\git

**Comment by unusualmutant** [comment] 2020-10-31 16:06
Ah of course, the other output is from the debian image, and my command line is windows. Sorry :)

**Comment by Shpota** [comment] 2020-10-31 18:33
@unusualmutant I have checked the same config on a Windows machine and I couldn't reproduce the issue. Is there a chance you changed some files (maybe unintentionally)? Could you please try generating a fresh project and see if `docker-compose up` works?

**Comment by unusualmutant** [comment] 2020-10-31 18:47
Hmm, interesting. I started from scratch, and `docker-compose up` worked, but I am still getting the same "errors" in Visual Studio Code about not being able to find `model`. But I guess that is an IDE issue.

Also, I'm getting a lot of deprecation warnings, is that expected?

![image](https://user-images.githubusercontent.com/50904772/97787346-d1ec0780-1bb1-11eb-867b-bfb665781058.png)

**Comment by Shpota** [comment] 2020-10-31 19:05
Deprecation warnings are expected. Angular 10.1 packages still have dependencies that are marked as deprecated.

As for the highlighting issues, it might be an issue of IDE as well as a missconfiguration of your go environment.

First, navigate to the `server` folder form the console and execute `go build .`. If the command finishes without an error the issue is in IDE. 

The generated project uses Go Modules. In order for such projects to work they must be placed outside of an `src` folder of GOPATH (find more details [here](https://blog.golang.org/using-go-modules)).
> As of Go 1.11, the go command enables the use of modules when the current directory or any parent directory has a go.mod, provided the directory is outside $GOPATH/src. (Inside $GOPATH/src, for compatibility, the go command still runs in the old GOPATH mode, even if a go.mod is found. See the go command documentation for details.) Starting in Go 1.13, module mode will be the default for all development.

I am not a user of VS Code, but I think you may want to try importing the `server` folder (the one that contains `go.mod` file)  as a root of a project into VS Code to make CS Code see the modules.

Please let me know if this helps?

**Comment by unusualmutant** [comment] 2020-10-31 19:25
Ok, thanks, nice to know about the deprecation.

I found out here: http://www.matthiassommer.it/programming/go-please-visual-studio-code-go-mod-go-language-server/ that I need to run this command: `setx GO111MODULE on` to enable modules. Doing that and restarting VS Code made it work.

So to sum up: I saw the errors in the IDE, tried to fix it, asked for help, tried `docker-compose up` which didn't work because I had broken the code in my attempts to fix the IDE error, started from scratch, saw that `docker-compose up` worked, found the go modules fix for VS Code.

Apologies for wasting your time, and many thanks for taking the time to help!

**Comment by Shpota** [comment] 2020-10-31 19:27
No problem. I am glad you found out how to fix the issue.

**Closed by Shpota** 2020-10-31 19:27 UTC
